x = [
    {
        "gl-cor:accountingEntries": 1,
        "gl-cor:entriesType": "other",
        "gl-cor:uniqueID": "001",
        "gl-cor:language": "iso639:en",
        "gl-cor:creationDate": "2005-07-05",
        "gl-bus:creator": "XBRL GL Working Group",
        "gl-cor:entriesComment": "A best practice listing of invoices instance document",
        "gl-cor:periodCoveredStart": "2005-06-01",
        "gl-cor:periodCoveredEnd": "2005-06-30",
        "gl-bus:sourceApplication": "XABRA",
        "gl-muc:defaultCurrency": "iso4217:usd",
        "gl-bus:organizationIdentifier": "ABC Company",
        "gl-bus:organizationDescription": "Company Name",
    },
    {
        "gl-cor:entryHeader": 1,
        "gl-cor:postedDate": "2005-07-01",
        "gl-cor:enteredBy": "Otto Wellwood",
        "gl-cor:enteredDate": "2005-07-01",
        "gl-cor:sourceJournalID": "pj",
        "gl-bus:sourceJournalDescription": "Vendor purchases journal",
        "gl-bus:entryOrigin": "imported entry",
        "gl-cor:entryNumber": "50",
        "gl-cor:entryComment": "Invoice: #51029 Vendor: #1130",
        "gl-cor:accountingEntries": 1,
    },
    {
        "gl-cor:entryDetail": 1,
        "gl-cor:lineNumber": "1",
        "gl-cor:amount": "500",
        "gl-cor:postingDate": "2005-06-30",
        "gl-bus:amountMemo": "false",
        "gl-cor:documentType": "voucher",
        "gl-cor:documentNumber": "51029",
        "gl-cor:documentReference": "Voucher#: 100900",
        "gl-cor:documentDate": "2005-06-15",
        "gl-bus:documentReceivedDate": "2005-06-14",
        "gl-bus:documentLocation": "Fred's desk drawer.",
        "gl-cor:detailComment": "Vendor#: 1130 Document#: 51029 Date: 6/15/05",
        "gl-cor:maturityDate": "2005-07-15",
        "gl-cor:terms": "2% 10 Net 30",
        "gl-cor:accountingEntries": 1,
        "gl-cor:entryHeader": 1,
        "gl-cor:identifierCode": "1130",
        "gl-cor:identifierDescription": "Rettaler Property Ltd",
        "gl-cor:identifierType": "V",
        "gl-bus:measurableCode": "IN",
        "gl-bus:measurableID": "Widget1",
        "gl-bus:measurableDescription": "Red Widger",
        "gl-bus:measurableQuantity": "100",
        "gl-bus:measurableUnitOfMeasure": "Each",
        "gl-bus:measurableCostPerUnit": "5",
    },
    {
        "gl-cor:entryDetail": 2,
        "gl-cor:lineNumber": "2",
        "gl-cor:amount": "300",
        "gl-cor:postingDate": "2005-06-30",
        "gl-bus:amountMemo": "false",
        "gl-cor:documentType": "voucher",
        "gl-cor:documentNumber": "51029",
        "gl-cor:documentReference": "Voucher#: 100900",
        "gl-cor:documentDate": "2005-06-15",
        "gl-bus:documentReceivedDate": "2005-06-14",
        "gl-bus:documentLocation": "Fred's desk drawer.",
        "gl-cor:detailComment": "Vendor#: 1130 Document#: 51029 Date: 6/15/05",
        "gl-cor:maturityDate": "2005-07-15",
        "gl-cor:terms": "2% 10 Net 30",
        "gl-cor:accountingEntries": 1,
        "gl-cor:entryHeader": 1,
        "gl-cor:identifierCode": "1130",
        "gl-cor:identifierDescription": "Rettaler Property Ltd",
        "gl-cor:identifierType": "V",
        "gl-bus:measurableCode": "IN",
        "gl-bus:measurableID": "Gidget3",
        "gl-bus:measurableDescription": "Sally Field of Dreams Edition",
        "gl-bus:measurableQuantity": "15",
        "gl-bus:measurableUnitOfMeasure": "Each",
        "gl-bus:measurableCostPerUnit": "20",
    },
    {
        "gl-cor:entryHeader": 2,
        "gl-cor:postedDate": "2005-07-01",
        "gl-cor:enteredBy": "Otto Wellwood",
        "gl-cor:enteredDate": "2005-07-01",
        "gl-cor:sourceJournalID": "pj",
        "gl-bus:sourceJournalDescription": "Vendor purchases journal",
        "gl-bus:entryOrigin": "imported entry",
        "gl-cor:entryNumber": "51",
        "gl-cor:entryComment": "Invoice: #4321 Vendor: #8765",
        "gl-cor:accountingEntries": 1,
    },
    {
        "gl-cor:entryDetail": 1,
        "gl-cor:lineNumber": "1",
        "gl-cor:amount": "54000",
        "gl-cor:postingDate": "2005-06-30",
        "gl-bus:amountMemo": "false",
        "gl-cor:documentType": "voucher",
        "gl-cor:documentNumber": "234",
        "gl-cor:documentReference": "Voucher#: 100901",
        "gl-cor:documentDate": "2005-06-15",
        "gl-bus:documentReceivedDate": "2005-06-14",
        "gl-bus:documentLocation": "Fred's desk drawer.",
        "gl-cor:detailComment": "Vendor#: 1412 Document#: 234 Date: 6/15/05",
        "gl-cor:maturityDate": "2005-07-15",
        "gl-cor:terms": "2% 10 Net 30",
        "gl-cor:accountingEntries": 1,
        "gl-cor:entryHeader": 2,
        "gl-cor:identifierCode": "1412",
        "gl-cor:identifierDescription": "Fitzsimmons Office Supplies",
        "gl-cor:identifierType": "V",
        "gl-bus:measurableCode": "IN",
        "gl-bus:measurableID": "4576",
        "gl-bus:measurableDescription": "Self Adjusting Paper Clips",
        "gl-bus:measurableQuantity": "2000",
        "gl-bus:measurableUnitOfMeasure": "Each",
        "gl-bus:measurableCostPerUnit": "27",
    },
    {
        "gl-cor:entryDetail": 2,
        "gl-cor:lineNumber": "2",
        "gl-cor:amount": "1500",
        "gl-cor:postingDate": "2005-06-30",
        "gl-bus:amountMemo": "false",
        "gl-cor:documentType": "voucher",
        "gl-cor:documentNumber": "234",
        "gl-cor:documentReference": "Voucher#: 100901",
        "gl-cor:documentDate": "2005-06-15",
        "gl-bus:documentReceivedDate": "2005-06-14",
        "gl-bus:documentLocation": "Fred's desk drawer.",
        "gl-cor:detailComment": "Vendor#: 1412 Document#: 234 Date: 6/15/05",
        "gl-cor:maturityDate": "2005-07-15",
        "gl-cor:terms": "2% 10 Net 30",
        "gl-cor:accountingEntries": 1,
        "gl-cor:entryHeader": 2,
        "gl-cor:identifierCode": "1412",
        "gl-cor:identifierDescription": "Fitzsimmons Office Supplies",
        "gl-cor:identifierType": "V",
        "gl-bus:measurableCode": "IN",
        "gl-bus:measurableID": "4800",
        "gl-bus:measurableDescription": "Self Expanding Paper Sheets",
        "gl-bus:measurableQuantity": "100",
        "gl-bus:measurableUnitOfMeasure": "Each",
        "gl-bus:measurableCostPerUnit": "15",
    },
    {
        "gl-cor:entryDetail": 3,
        "gl-cor:lineNumber": "3",
        "gl-cor:amount": "500",
        "gl-cor:postingDate": "2005-06-30",
        "gl-bus:amountMemo": "false",
        "gl-cor:documentType": "voucher",
        "gl-cor:documentNumber": "234",
        "gl-cor:documentReference": "Voucher#: 100901",
        "gl-cor:documentDate": "2005-06-15",
        "gl-bus:documentReceivedDate": "2005-06-14",
        "gl-bus:documentLocation": "Fred's desk drawer.",
        "gl-cor:detailComment": "Vendor#: 1412 Document#: 234 Date: 6/15/05",
        "gl-cor:maturityDate": "2005-07-15",
        "gl-cor:terms": "2% 10 Net 30",
        "gl-cor:accountingEntries": 1,
        "gl-cor:entryHeader": 2,
        "gl-cor:identifierCode": "1412",
        "gl-cor:identifierDescription": "Fitzsimmons Office Supplies",
        "gl-cor:identifierType": "V",
        "gl-bus:measurableCode": "IN",
        "gl-bus:measurableID": "120",
        "gl-bus:measurableDescription": "Waste Basket",
        "gl-bus:measurableQuantity": "50",
        "gl-bus:measurableUnitOfMeasure": "Each",
        "gl-bus:measurableCostPerUnit": "10",
    },
]
